hmcts/am-org-role-mapping-service

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/requirements.yaml
Updated the java chart version.
```
[ ] Yes
[ ] No
```
=> Updated the java chart version.

build.gradle, config/owasp/suppressions.xml
Suppressing the Oauth vulnerabilities.
```
[ ] Yes
[x] No
```
=> Suppressing the Oauth vulnerabilities.

docker-compose.yml, src/main/resources/application.yaml
=> Updating the vault secrets

src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/configuration/FeignClientInterceptor.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/oidc/IdamRepository.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/TopicConsumer.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/deserializer/Deserializer.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/deserializer/OrmCallbackDeserializer.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/deserializer/OrmDeserializer.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-1035
Azure config changes and token generation
```
[ ] Yes
[x ] No
```
=> AM-1035:Azure config changes and token generation

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/configuration/CRDFeignClientFallback.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/configuration/FeignClientInterceptor.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/UserAccessProfileBuilder.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/SecurityUtils.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/SecurityUtilsTest.java
https://tools.hmcts.net/jira/browse/AM-1097
Junit to follow the TDD Process.
```
[ ] Yes
[x ] No
```
=> AM-1089- Junit test cases to follow the TDD process for ORM development.

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/requirements.yaml
https://tools.hmcts.net/jira/browse/AM-1105
```
[ ] Yes
[X] No
```
=> Update chart versions

Jenkinsfile_CNP, src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrgRoleMappingAmTestAutomationAdapter.java, src/functionalTest/resources/features/F-001/F-001-Base-Root.td.json, src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/F-001_Test_Data_Base.td.json, src/functionalTest/resources/features/F-001/S-001.td.json, src/functionalTest/resources/features/F-001/S-001_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-001/S-002.td.json, src/functionalTest/resources/features/F-001/S-002_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/common/ResponseRequestedRole.td.json, src/functionalTest/resources/features/common/ResponseRoleRequest.td.json
https://tools.hmcts.net/jira/browse/AM-1089
https://tools.hmcts.net/jira/browse/AM-1100
Added functional tests.
[x] Yes
[ ] No
=> AM-1100: Functional tests.

Jenkinsfile_CNP, Jenkinsfile_nightly, src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/S-001_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-001/S-002_DeleteDataForRoleAssignments.td.json, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-1100
ORM Functional Tests
[ ] Yes
[x] No
=> AM-1100: ORM functional tests

pacts/am_org_role_mapping-am_role_assignment_service.json, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTest.java
https://tools.hmcts.net/jira/browse/AM-1115
Added three additional consumer PACT for create role assignment endpoint interaction from ORM to RAS.
```
[ ] Yes
[ x] No
```
=> Am 1115 pact consumer

Jenkinsfile_CNP, Jenkinsfile_nightly, pacts/am_org_role_mapping-am_role_assignment_service.json, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrgRoleMappingAmTestAutomationAdapter.java, src/functionalTest/resources/features/F-001/F-001-Base-Root.td.json, src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/F-001_Test_Data_Base.td.json, src/functionalTest/resources/features/F-001/S-001.td.json, src/functionalTest/resources/features/F-001/S-001_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-001/S-002.td.json, src/functionalTest/resources/features/F-001/S-002_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/common/ResponseRequestedRole.td.json, src/functionalTest/resources/features/common/ResponseRoleRequest.td.json, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-1116
```
[ ] Yes
[X] No
```
=> Sync with Master - Demo

Jenkinsfile_CNP, Jenkinsfile_nightly, pacts/am_org_role_mapping-am_role_assignment_service.json, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrgRoleMappingAmTestAutomationAdapter.java, src/functionalTest/resources/features/F-001/F-001-Base-Root.td.json, src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/F-001_Test_Data_Base.td.json, src/functionalTest/resources/features/F-001/S-001.td.json, src/functionalTest/resources/features/F-001/S-001_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-001/S-002.td.json, src/functionalTest/resources/features/F-001/S-002_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/common/ResponseRequestedRole.td.json, src/functionalTest/resources/features/common/ResponseRoleRequest.td.json, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-1116
```
[ ] Yes
[X] No
```
=> Sync with Master - PerfTest

build.gradle, charts/am-org-role-mapping-service/values.yaml, docker-compose.yml, src/main/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingApplication.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/UserRequest.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RoleAssignmentService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/oidc/IdamRepository.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/RetrieveDeadLetterTopic.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/TopicConsumer.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/TopicConsumerBk.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/deserializer/Deserializer.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/deserializer/OrmDeserializer.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/messaging/MessagingConfig.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/SecurityUtils.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yml
azure service bus integration
```
[ ] Yes
[ ] No
```
=> Am 1107 azure service bus integration

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/AM-1137
```
[ ] Yes
[X] No
```
=> Commit branch sync changes

build.gradle, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolBase.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCaseMappingTest.java
https://tools.hmcts.net/jira/browse/AM-1133
Added tests for drool scenarios on case mapping in ORM.
```
[ ] Yes
[x ] No
```
=> Drool scenarios testing for case mapping.

build.gradle, pacts/am_org_role_mapping-am_role_assignment_service_create.json, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForCreate.java
https://tools.hmcts.net/jira/browse/AM-1128
=> AM-1128 - Pact Consumer - Create Api - Additional Scenarios 

build.gradle, src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/advice/OrgRoleMappingControllerAdviceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/launchdarkly/FeatureConditionEvaluatorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/SecurityUtilsTest.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
https://tools.hmcts.net/jira/browse/AM-1135
Improve unit and mutation coverage.
```
[ ] Yes
[x ] No
```
=> Am 1135 unit mutation testing

bin/sendMessage.sh, build.gradle, charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.preview.template.yaml, charts/am-org-role-mapping-service/values.yaml, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/TopicConsumer.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yml, src/smokeTest/java/uk/gov/hmcts/reform/orgrolemapping/SmokeTest.java
Reverts hmcts/am-org-role-mapping-service#51
=> Revert "AM-1131- enable asb for higher env."

src/main/resources/bootstrap.yml
=> Remove s2s mount reference

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/advice/OrgRoleMappingControllerAdvice.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/AssignmentRequest.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/RoleAssignmentRequestResource.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtils.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/advice/OrgRoleMappingControllerAdviceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java
Handle unprocessedEntity exception from RAS
```
[ ] Yes
[x ] No
```
=> Handle unprocessedEntity exception from RAS

bin/sendMessage.sh, build.gradle, charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.preview.template.yaml, charts/am-org-role-mapping-service/values.yaml, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/TopicConsumer.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yml, src/smokeTest/java/uk/gov/hmcts/reform/orgrolemapping/SmokeTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/TopicConsumerTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/SecurityUtilsTest.java
=> enable asb for higher env.

config/owasp/suppressions.xml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-1158
=> AM-1158 Addressing CVEs

pacts/am_org_role_mapping-am_role_assignment_service_search_query.json, pacts/am_org_role_mapping-crd_case_worker_ref_service.json, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForCRD.java, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForSearchQuery.java
https://tools.hmcts.net/jira/browse/AM-1154
ORM consumer pact test for CRD
[ ] Yes
[x] No
=> AM-1154: ORM consumer pact test

pacts/am_org_role_mapping-am_role_assignment_service_delete_actor.json, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForDelete.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-1026
=> AM-1026 pact consumer for delete api

pacts/am_org_role_mapping-am_role_assignment_service_create.json, pacts/am_org_role_mapping-am_role_assignment_service_get_actor_by_id.json, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForCreate.java, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForGetActorById.java
https://tools.hmcts.net/jira/browse/AM-1164
=> AM-1164 removed expectation of links object in pacts

src/functionalTest/resources/features/F-001/S-001.td.json, src/functionalTest/resources/features/F-001/S-002.td.json
=> updated the ras response.

pacts/am_org_role_mapping-am_role_assignment_service_delete_actor.json, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForDelete.java
https://tools.hmcts.net/jira/browse/AM-1164
=> AM-1164 updated delete pact name

charts/am-org-role-mapping-service/values.preview.template.yaml, pacts/am_org_role_mapping-crd_case_worker_ref_service.json, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForCRD.java, src/functionalTest/resources/features/common/CreateSingleUserProfileCrd.td.json, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/helper/IntTestDataBuilder.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/UserAccessProfile.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/UserProfile.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilder.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/UserAccessProfileBuilder.java, src/main/resources/userProfileSample.json, src/main/resources/validationrules/iac/iac-caseworker-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCaseMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
Change delete_flag to suspended
Change delete_flag to suspended
```
[ ] Yes
[ ] No
```
=> Master fix: Change delete_flag to suspended

src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrgRoleMappingAmTestAutomationAdapter.java
Changing the domain to justice.gov.uk in functional tests.
Changing the domain to justice.gov.uk in functional tests.
```
[ ] Yes
[x] No
```
=> Changing the domain to justice.gov.uk in functional tests.

src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/helper/IntTestDataBuilder.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java
=> Am 1178 primary location issue

build.gradle, charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.aat.template.yaml, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingApplication.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/oidc/IdamRepository.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/orgrolemapping/oidc/IdamRepositoryTest.java
https://tools.hmcts.net/jira/browse/AM-1182
=> AM-1182 caffeine cache implementation

charts/am-org-role-mapping-service/Chart.yaml
=> updated charts to match organisation standards

build.gradle
=> disabling kotlin

build.gradle
https://tools.hmcts.net/jira/browse/AM-1196
=> AM-1196 upgrading failing dependency

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/requirements.yaml, charts/am-org-role-mapping-service/values.yaml
=> updating the orm aat topic name to rd-caseworker-subscription-aat

build.gradle, pacts/am_org_role_mapping-am_role_assignment_service_get_actor_by_id.json, pacts/am_org_role_mapping-am_role_assignment_service_roles.json, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForGetActorById.java, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForStaticRoles.java
=> Pact fix for roleCategory

charts/am-org-role-mapping-service/values.yaml
=> updated the subscription name based upon env

build.gradle
https://tools.hmcts.net/jira/browse/AM-1220
=> tomcat upgrade

build.gradle
https://tools.hmcts.net/jira/browse/AM-1220
=> fix springfox version

build.gradle
Fix build issues
```
[ ] Yes
[X] No
```
=> Fix build issues

src/main/resources/application.yaml
=> Updated the ORM admin account

charts/am-org-role-mapping-service/values.ithc.template.yaml
=> Adding ithc file.

build.gradle
=> Netty CVE Fix

Jenkinsfile_CNP, build.gradle, charts/am-org-role-mapping-service/values.preview.template.yaml, charts/am-org-role-mapping-service/values.yaml, docker-compose.yml, docker/database/Dockerfile, docker/database/init-db.sh, infrastructure/main.tf, infrastructure/variables.tf, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/BaseTest.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yml, src/main/resources/db/migration/V1.1__init_tables.sql, src/smokeTest/java/uk/gov/hmcts/reform/orgrolemapping/BaseTest.java, src/smokeTest/java/uk/gov/hmcts/reform/orgrolemapping/SmokeTest.java
https://tools.hmcts.net/jira/browse/AM-1263
add database in orm service
```
[ ] Yes
[ ] No
```
=> Am 1263 add database in orm service

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrgRoleMappingAmTestAutomationAdapter.java
https://tools.hmcts.net/jira/browse/AM-1288
=> AM-1288 Upgrading netty to avoid CVE

src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RoleAssignmentServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/ValidationUtilTest.java
Jira Link: https://tools.hmcts.net/jira/browse/AM-1279
=> AM-1279 mutation test coverage

README.md
https://tools.hmcts.net/jira/browse/AM-1312
Added the read me file
```
[ ] Yes
[x] No
```
=> added the read me file for ORM

charts/am-org-role-mapping-service/Chart.yaml
=> chart version update

build.gradle
=> CVE Fix for commons-io

Jenkinsfile_CNP, src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrgRoleMappingAmTestAutomationAdapter.java
https://tools.hmcts.net/jira/browse/AM-1321
=> AM-1321 Integration and pact consumer test reports in Jenkins

build.gradle, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/configuration/CRDFeignClientFallback.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/configuration/JRDFeignClientFallback.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/UserAccessProfileBuilder.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/CaseWorkerAccessProfileBuilderTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/oidc/JwtGrantedAuthoritiesConverterTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/ValidationUtilTest.java
Jira link: https://tools.hmcts.net/jira/browse/AM-1311
=> AM-1311 Mutation Test Improvements

build.gradle, src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/SecurityConfiguration.java
NA
Fix console errors
```
[ ] Yes
[x] No
```
=> Fix console errors

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrgRoleMappingAmTestAutomationAdapter.java, src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/TestDataLoaderMain.java
NA
(feat): Migrating to Jitpack.
```
[ ] Yes
[x] No
```
=> (feat): Migrating to Jitpack.

Jenkinsfile_nightly
NA
(feat): Fixing the nightly builds.
```
[ ] Yes
[x] No
```
=> (feat): Fixing the nightly builds.

src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrgRoleMappingAmTestAutomationAdapter.java, src/functionalTest/resources/features/F-001/F-001.feature
NA
(feat): Updating the functional test cases.
```
[ ] Yes
[x] No
```
=> (feat): Updating the functional test cases.

build.gradle
=> Spring upgrade

src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/JobConfiguration.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/data/RefreshJobEntity.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/Request.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/RoleAssignment.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestrator.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/configuration/CRDFeignClientFallback.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/UserAccessProfileBuilder.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/CRDServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PersistenceServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RoleAssignmentServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/UserAccessProfileBuilderTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/ValidationUtilTest.java
Jira Link: https://tools.hmcts.net/jira/browse/AM-1368
=> AM-1368 JUnit testing for Refresh API ORM

src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/MessagingConfiguration.java
https://tools.hmcts.net/jira/browse/AM-1423
Fixing the environment variable value.
```
[ ] Yes
[x] No
```
=> Fixing the environment variable value.

build.gradle, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestrator.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingService.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PersistenceServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
https://tools.hmcts.net/jira/browse/AM-1416
=> 1416 testing service layer

src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/data/GenericArrayUserTypeTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/ValidationUtilTest.java
Jira link: https://tools.hmcts.net/jira/browse/AM-1417
=> Am 1417 mutation coverage refresh api

build.gradle
=> Removing sonar exclusion am 1335

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.yaml, src/main/resources/application.yaml
Fixing the application logging level.
```
[ ] Yes
[x] No
```
=> Fixing the application logging level.

src/contractTest/java/uk/gov/hmcts/reform/refdata/RefDataCaseworkerConsumerTest.java
https://tools.hmcts.net/jira/browse/AM-1425
1. PACT Consumer test CRD API /refdata/internal/staff/usersByServiceName
```
[ ] Yes
[X ] No
```
=> AM 1425 PACT consumer test for CRD API

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/am-org-role-mapping-service/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/AM-1425
Minor fix to point master
```
[ ] Yes
[x] No
```
=> Updated the RAS URL to point to master for all FTA

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle
https://tools.hmcts.net/jira/browse/AM-1459
Fix the breaking BEFTA library.
```
[ ] Yes
[x] No
```
=> Fix the functional test.

.github/workflows/autoupdate.yml
https://tools.hmcts.net/jira/browse/AM-1420
```
[ ] Yes
[X] No
```
=> Add autoupdate config for PRs

src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForSearchQuery.java
https://tools.hmcts.net/jira/browse/AM-1435
Do not Merge this PR. It will be merged along with advance query API merge in the RAS application otherwise this test pact would fail in master.
=> AM-1435 pact for advanced search query api - Do not Merge this PR

charts/am-org-role-mapping-service/Chart.yaml
https://tools.hmcts.net/jira/browse/AM-1540
Update the chart version.
```
[ ] Yes
[x] No
```
=> Updated the chart version.

src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForAdvanceDelete.java
Jira Link: https://tools.hmcts.net/jira/browse/AM-1510
=> Am 1510 pact consumer test advance delete

build.gradle
https://tools.hmcts.net/jira/browse/AM-1550
Fix the CVE CVE-2021-28170
```
[ ] Yes
[x] No
```
=> Fixing the CVE's

build.gradle
AM-1550
Fixing the CVE CVE-2021-22119
```
[ ] Yes
[x] No
```
=> Fixing the CVE's CVE-2021-22119

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-1579
=> 1579 CVE nimbus lang tang

src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForStaticRoles.java
https://tools.hmcts.net/jira/browse/AM-1576
=> disabling static roles pact

src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolAdminOrgRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCaseMappingTest.java
https://tools.hmcts.net/jira/browse/AM-1622
ORG and Admin roles
```
[ ] Yes
[X ] No
```
=> refactoring ORG and Admin roles junits

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-1605
=> 1605 - Removing secrets

src/main/resources/application.yaml
Jira link: https://tools.hmcts.net/jira/browse/AM-1666
=> Fortify scan issue fix

Jenkinsfile_nightly, build.gradle, src/test/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/CRDTopicConsumerTest.java
Fixing the Pitest.
```
[ ] Yes
[x] No
```
=> Fixing the Pitest.

build.gradle
Reverts hmcts/am-org-role-mapping-service#480
=> Revert "Bump postgresql from 42.2.14 to 42.3.1"

infrastructure/main.tf
NA
Configure postgres version to 9.6
```
[ ] Yes
[X] No
```
=> Configure postgres version

build.gradle
CVE-2021-22096 fix
```
[ ] Yes
[x] No
```
=> CVE-2021-22096 fix

infrastructure/main.tf
=> Update db secrets v11 - PerfTest

infrastructure/main.tf
Updating the pwd for DB
```
[ ] Yes
[x] No
```
=> Updating the pwd for DB

infrastructure/main.tf
Create DB V11 secret using terraform.
```
[ ] Yes
[x] No
```
=> Create DB V11 secret using terraform.

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.aat.template.yaml, charts/am-org-role-mapping-service/values.yaml, infrastructure/main.tf
Update the values.yaml to point to new V11 DB.
```
[ ] Yes
[x] No
```
=> Update the values.yaml to point to new V11 DB.

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-1788
v11 DB migration completed. Remove v9.6 DB.
```
[ ] Yes
[X ] No
```
=> Remove v9.6 DB

src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/JRDUserRequest.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JRDService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/JRDFeignClient.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/configuration/JRDFeignClientFallback.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/JRDTopicConsumer.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/CaseWorkerAccessProfileBuilderTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
Logs and pagesizing for jrd profiles
```
[ ] Yes
[ X] No
```
=> JRD paging and logs

build.gradle, src/functionalTest/resources/features/F-003/S-021.td.json, src/functionalTest/resources/features/F-003/S-022.td.json, src/functionalTest/resources/features/F-003/S-023.td.json, src/functionalTest/resources/features/F-003/S-024.td.json, src/main/resources/validationrules/iac/iac-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolJrdOfficeOrgRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolJudicialMappingTest.java
https://tools.hmcts.net/jira/browse/AM-1800
fixing the incorrect work types for judicial roles.
```
[ ] Yes
[x] No
```
=> fixing the incorrect work types for judicial roles.

src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/ValidationUtilTest.java
https://tools.hmcts.net/jira/browse/AM-1792
=> fixing failing validate date test

src/functionalTest/resources/features/F-001/S-006.td.json, src/functionalTest/resources/features/F-003/S-021.td.json, src/functionalTest/resources/features/F-003/S-022.td.json, src/functionalTest/resources/features/F-003/S-023.td.json
Fixing the build.
```
[ ] Yes
[x] No
```
=> Fixing the build.

Jenkinsfile_nightly
=> Fortify was disabled for nightly build.

Jenkinsfile_nightly
=> Changed the nightly time lines

src/test/java/uk/gov/hmcts/reform/orgrolemapping/oidc/IdamRepositoryTest.java
removed junk token
```
[ ] Yes
[X ] No
```
=> test case fix

Jenkinsfile_nightly
=> disabling these steps temporarily

Jenkinsfile_nightly
=> enabling steps

src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshController.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/advice/OrgRoleMappingControllerAdvice.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/advice/OrgRoleMappingControllerAdviceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JRDServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialBookingServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialRefreshOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java
https://tools.hmcts.net/jira/browse/AM-1849
Integration tests for judicial refresh api
```
[ ] Yes
[ X] No
```
=> Intgegration test for orm refresh with bookings

Jenkinsfile_nightly, config/fortify-client.properties
https://tools.hmcts.net/jira/browse/AM-1867
Update fortify release ID and enable Fortify scan
```
[ ] Yes
[X] No
```
=> Update fortify release ID and enable Fortify scan

src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java
fortify scan fix
```
[ ] Yes
[X ] No
```
=> Am fortify fix

src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/advice/OrgRoleMappingControllerAdviceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/CaseWorkerAccessProfileBuilderTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/oidc/IdamRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/SecurityUtilsTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/ValidationUtilTest.java
• [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/AM-1863
Improve ORM conditional coverage.
```
[ ] Yes
[x ] No
```
=> AM_1863 sonar conditional coverage

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/reform/judicialbooking/JudicialBookingCreateConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/judicialbooking/JudicialBookingQueryConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/provider/OrgRoleMappingProviderTestForRefresh.java, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/provider/ProviderTestConfiguration.java
https://tools.hmcts.net/jira/browse/AM-1876
=> Create Judicial Booking Consumer Pact Test

src/functionalTest/resources/features/F-004/F-004.feature
orm fta updated inline with correct LD flag 
```
[ ] Yes
[x] No
```
=> orm fta updated inline with correct LD flag 

Jenkinsfile_CNP, build.gradle
https://tools.hmcts.net/jira/browse/AM-1918
=> Fix ORM Pact Verification Publish to Remote Broker

README.md, src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/S-002.td.json, src/functionalTest/resources/features/F-001/S-006.td.json, src/functionalTest/resources/features/F-001/S-010.td.json, src/functionalTest/resources/features/F-003/F-003.feature
=> Test PR for FTA with IAC 2_0 flag

src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-001/S-007.td.json
https://tools.hmcts.net/jira/browse/AM-1933
Testing the ORM and RAS FTA with WA R2 features enabled
```
[ ] Yes
[x] No
```
=> updated scenario 7 to identify duplicate

Jenkinsfile_CNP, build.gradle
Added Kubernetes Vars for Pact Remote
=> Fix Pact Publish

build.gradle
removing deprecated jcenter
```
[ ] Yes
[x] No
```
=> removing deprecated jcenter

src/functionalTest/resources/features/F-003/F-003.feature, src/functionalTest/resources/features/F-004/F-004.feature, src/main/resources/application.yaml
=> Temp disable failing FTA

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingService.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java
expired profiles has to remove from RAS
```
[ ] Yes
[X ] No
```
=> empty request refresh in RAS from orm

src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/provider/ProviderTestConfiguration.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/CaseWorkerAccessProfile.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/JudicialAccessProfile.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/JudicialProfile.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/UserAccessProfile.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialRefreshOrchestrator.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestrator.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilder.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialRefreshOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java
https://tools.hmcts.net/jira/browse/AM-1923
=> Addressing sonar smell: usage of wildcard type

src/main/resources/application.yaml
=> dummy commit to rebuild ORM master

charts/am-org-role-mapping-service/Chart.yaml
=> Upgrade java chart version

charts/am-org-role-mapping-service/Chart.yaml
=> Upgrade chart version

src/functionalTest/resources/features/F-003/F-003.feature
https://tools.hmcts.net/jira/browse/AM-2040
```
[ ] Yes
[x] No
```
=> disable failing judicial scenarios

src/functionalTest/resources/features/F-003/F-003.feature, src/functionalTest/resources/features/F-003/JRDTribunalJudgeFeepaidUser.td.json, src/functionalTest/resources/features/F-003/JRDTribunalJudgeSalariedUser.td.json, src/functionalTest/resources/features/F-003/S-022.td.json, src/functionalTest/resources/features/F-003/S-023.td.json, src/functionalTest/resources/features/F-004/F-004.feature, src/functionalTest/resources/features/F-004/S-031.td.json, src/functionalTest/resources/features/F-004/S-032.td.json
https://tools.hmcts.net/jira/browse/AM-1994
FTA fix.
[ ] Yes
[x] No
=> AM-1994: FTA fix.

charts/am-org-role-mapping-service/Chart.yaml
=> Updated the chart version

build.gradle, charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.preview.template.yaml, charts/am-org-role-mapping-service/values.yaml, src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/LDDummyClient.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/LaunchDarklyConfiguration.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/launchdarkly/FeatureConditionEvaluator.java, src/main/resources/application.yaml
- [x ] commit messages are meaningful and follow good commit message guidelines
```
[ ] Yes
[x ] No
```
=> LD load on startup based on yml flag

build.gradle
https://tools.hmcts.net/jira/browse/AM-2065
```
[ ] Yes
[x] No
```
=> updated some jar bumps

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2009
CVE FIx for drools
```
[ ] Yes
[x] No
```
=> upgrade drools to remove cve suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2067
=> Fix CVE-2018-1258

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForStaticRoles.java, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/BaseTest.java, src/smokeTest/java/uk/gov/hmcts/reform/orgrolemapping/BaseTest.java
https://tools.hmcts.net/jira/browse/AM-2068
gradle upgrade to 7.4.1
```
[ ] Yes
[ X] No
```
=> gradle upgrade to 7.4.1

build.gradle
=> Updated poi, poi-ooxml & poi-scratchpad to 5.2.1

build.gradle
https://tools.hmcts.net/jira/browse/AM-2098
postgres version update
```
[ ] Yes
[x] No
```
=> postgres version update

src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrmDefaultMultiSourceFeatureToggleService.java, src/functionalTest/resources/features/F-003/F-003.feature, src/functionalTest/resources/features/F-003/S-022.td.json
FTA fix for master build
```
[ ] Yes
[ X] No
```
=> removed hearting FTA

build.gradle
https://tools.hmcts.net/jira/browse/AM-2104
multiple cve fixes
```
[ ] Yes
[x] No
```
=> multiple cve fixes

charts/am-org-role-mapping-service/Chart.yaml
helm chart update
```
[ ] Yes
[X ] No
```
=> Am helpchart update

build.gradle
=> CVE fix netty-version update

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/CaseWorkerAccessProfile.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilder.java, src/main/resources/validationrules/civil/civil-admin-mapping.drl, src/main/resources/validationrules/civil/civil-caseworker-mapping.drl, src/main/resources/validationrules/civil/civil-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolJudicialRoleMappingCivilTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
https://tools.hmcts.net/jira/browse/AM-2186
staff mapping rules for ORM
```
[ ] Yes
[x] No
```
=> staff mapping rules for ORM

src/main/resources/validationrules/civil/civil-judicial-org-role-mapping.drl
=> updated civil role worktype

src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolJudicialRoleMappingCivilTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
https://tools.hmcts.net/jira/browse/AM-2162
=> Added drool test scenarios for civil judicial roles

src/functionalTest/resources/features/F-005/F-005.feature, src/functionalTest/resources/features/F-005/S-044.td.json, src/functionalTest/resources/features/F-005/S-044_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-005/S-044_PostCreateRequestToORM.td.json
https://tools.hmcts.net/jira/browse/AM-2208
FTA for SSCS multi-region
```
[ ] Yes
[X ] No
```
=> FTA for multi region sscs

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilder.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java
Location check fix
```
[ ] Yes
[X ] No
```
=> location check for iac removed

src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestrator.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/oidc/IdamRepository.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/JRDTopicConsumer.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java
https://tools.hmcts.net/jira/browse/AM-2235
Empty profiles or invalid profiles has to remove from RAs
```
[ ] Yes
[X ] No
```
=> remove expired profile roles

src/functionalTest/resources/features/F-005/S-043.td.json
registaror ORG role substantive fix
```
[ ] Yes
[ X] No
```
=> FTA fix for registaror org role

src/functionalTest/resources/features/F-000/F-000.feature, src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-007/F-007.feature
=> updated different strings to DB for referring DB based flags

src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolJudicialRoleMappingCivilTest.java
Jun it for CIVIL judge and cercute-judge
```
[ ] Yes
[X ] No
```
=> CIVIL booking judge changes

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestrator.java, src/main/resources/validationrules/civil/civil-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolJudicialRoleMappingCivilTest.java
=> A change to the civil drool rules, added junit changes

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/AM-2289
```
[ ] Yes
[X] No
```
=> ORM:java version in helm repo version update

build.gradle
https://tools.hmcts.net/jira/browse/AM-2291
```
[ ] Yes
[X] No
```
=> ORM:Merge renovate bot pr's

build.gradle, charts/am-org-role-mapping-service/Chart.yaml
downgrade pact plugin
```
[ ] Yes
[ X] No
```
=> Downgrade pact

src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/DBFlagConfigurtion.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtils.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/ValidationUtil.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCaseMappingTest.java
https://tools.hmcts.net/jira/browse/AM-2305
```
[ ] Yes
[X] No
```
=> ORM:Code smell fix for RAS and ORM

src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PersistenceServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/launchdarkly/FeatureConditionEvaluatorTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtilsTest.java
https://tools.hmcts.net/jira/browse/AM-2307
```
[ ] Yes
[X] No
```
=> increasing code coverage and mutations

src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PersistenceServiceTest.java
Junjt fix for environment specific mock
```
[ ] Yes
[ X] No
```
=> fix junit failure in master

build.gradle, docker/database/Dockerfile, infrastructure/terraform.tf
Merging the renovate PR 16 Aug 2022
```
[ ] Yes
[X] No
```
=> merging the renovate PR

src/main/resources/validationrules/core/hearing-role-admin-global.drl, src/main/resources/validationrules/core/hearing-role-caseworker-global.drl, src/main/resources/validationrules/core/hearing-role-judicial-global.drl, src/main/resources/validationrules/core/utility-functions.drl, src/main/resources/validationrules/privatelaw/privatelaw-judicial-office-holder-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java
https://tools.hmcts.net/jira/browse/AM-2331
Hearing roles for private law
```
[ ] Yes
[X ] No
```
=> Am privatelaw hearing

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2380
=> Addressing CVE

charts/am-org-role-mapping-service/Chart.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2398
=> 2398 fix ld CVE

build.gradle
https://tools.hmcts.net/jira/browse/AM-2404
```
[ ] Yes
[X] No
```
=> CVE issues and build failures

charts/am-org-role-mapping-service/values.yaml, src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/JobConfiguration.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestrator.java
https://tools.hmcts.net/jira/browse/AM-2004
whitelist refresh batch job
```
[ ] Yes
[ X] No
```
=> white list refresh batch service

build.gradle
=> fix build failure

build.gradle, infrastructure/terraform.tf
=> fix-Nightly Build failure

src/functionalTest/resources/features/F-007/S-084.td.json, src/main/resources/validationrules/civil/civil-judicial-office-holder-mapping.drl, src/main/resources/validationrules/civil/civil-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java
https://tools.hmcts.net/jira/browse/AM-2448
https://tools.hmcts.net/jira/browse/AM-2449
=> Remove CFT Region and refactor Appointments

charts/am-org-role-mapping-service/values.preview.template.yaml, src/functionalTest/resources/features/common/users/CrdBeftaUser1.td.json
=> fix_fortify

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2505
```
[ ] Yes
[X] No
```
=> AM-Nightly Build Failure

src/functionalTest/resources/features/F-003/JRDTribunalJudgeFeepaidUser.td.json
FTA fix for judicial booking
```
[ ] Yes
[ X] No
```
=> judicial booking fta fix

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2575
```
[ ] Yes
[X] No
```
=> AM-Application Nightly Build Failed on CVE

src/main/resources/validationrules/publiclaw/publiclaw-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawJudicialRoleMappingTest.java
=> Public law judicial changes

src/main/resources/validationrules/core/hearing-role-caseworker-global.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java
=> FAMILY_PRIVATE_LAW - update hearing role id

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestrator.java
log enable
```
[ ] Yes
[X ] No
```
=> adding logs in orm

src/main/resources/validationrules/core/hearing-role-judicial-global.drl, src/main/resources/validationrules/publiclaw/publiclaw-judicial-office-holder-mapping.drl, src/main/resources/validationrules/publiclaw/publiclaw-judicial-org-role-mapping.drl
=> public law judicial change

src/main/resources/validationrules/publiclaw/publiclaw-judicial-office-holder-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawJudicialRoleMappingTest.java
=> designated family judge changes

build.gradle
https://tools.hmcts.net/jira/browse/AM-2630
```
[ ] Yes
[X] No
```
=> ORM-Nightly Build failed

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2636
```
[ ] Yes
[X] No
```
=> dependency check upgrade

src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCtscOrgRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawStaffOrgRolesTest.java
https://tools.hmcts.net/jira/browse/AM-2469
```
[ ] Yes
[x] No
```
=> Fix Code smell issues

src/main/resources/validationrules/core/hearing-role-admin-global.drl, src/main/resources/validationrules/core/hearing-role-caseworker-global.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java
https://tools.hmcts.net/jira/browse/AM-2655
```
[ ] Yes
[x] No
```
=> SSCS_HEARING - Add new business roles for SSCS

build.gradle
https://tools.hmcts.net/jira/browse/AM-2664
```
[ ] Yes
[X] No
```
=> swagger changes

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2668
```
[ ] Yes
[X] No
```
=> ORM:Application Nightly build failed due to CVE-2022-45688

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-2010
```
[ ] Yes
[x] No
```
=> Fix warnings

Jenkinsfile_CNP
=> fix orm build

Jenkinsfile_CNP, src/functionalTest/resources/features/F-007/S-061.td.json, src/functionalTest/resources/features/F-007/S-062.td.json, src/functionalTest/resources/features/F-007/S-063.td.json, src/functionalTest/resources/features/F-007/S-081.td.json, src/functionalTest/resources/features/F-007/S-082.td.json, src/functionalTest/resources/features/F-007/S-084.td.json, src/main/resources/validationrules/core/hearing-role-admin-global.drl, src/main/resources/validationrules/core/hearing-role-caseworker-global.drl, src/main/resources/validationrules/core/hearing-role-ctsc-global.drl, src/main/resources/validationrules/core/hearing-role-judicial-global.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilHearingJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java
https://tools.hmcts.net/jira/browse/AM-2362
```
[ ] Yes
[X] No
```
=> ORM:CIVIL_HMC - Add hearing roles for Civil service

build.gradle
https://tools.hmcts.net/jira/browse/AM-2681
```
[ ] Yes
[X] No
```
=> ORM and Refresh Batch-Application Nightly Build failed

build.gradle
https://tools.hmcts.net/jira/browse/AM-2686
=> AM-2686:Pact fix for reading from Project instead of System

charts/am-org-role-mapping-service/Chart.yaml
helm upgrade
```
[ ] Yes
[ X] No
```
=> helm upgrade

build.gradle, src/functionalTest/resources/features/F-003/S-021.td.json, src/functionalTest/resources/features/F-003/S-022.td.json, src/functionalTest/resources/features/F-003/S-024.td.json, src/functionalTest/resources/features/F-007/S-084.td.json, src/functionalTest/resources/features/F-008/S-073.td.json, src/integrationTest/resources/RASTribunalJudgeFeePaid.json
https://tools.hmcts.net/jira/browse/AM-2685
```
[ ] Yes
[X] No
```
=> ORM:Change in mappings for fee paid judges for services

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2733
CVE-2023-28708 tomcat
```
[ ] Yes
[ x] No
```
=> AM-2733 CVE-2023-28708 Suppression

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V2.1__iac_wa_1_2_base_flag_addition.sql, src/main/resources/validationrules/iac/iac-ctsc-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCtscOrgRoleMappingTest.java
https://tools.hmcts.net/jira/browse/AM-2732
> NB: dependent on hmcts/am-role-assignment-service#1864
```
[ ] Yes
[ *] No
```
=> AM-2732:CA & TS new role mapping for IAC - CTSC

src/functionalTest/resources/features/F-007/F-007.feature, src/functionalTest/resources/features/F-007/S-061.td.json, src/functionalTest/resources/features/F-007/S-061.v1_1.td.json, src/functionalTest/resources/features/F-007/S-062.td.json, src/functionalTest/resources/features/F-007/S-063.td.json, src/functionalTest/resources/features/F-007/S-064.td.json, src/functionalTest/resources/features/F-007/S-081.td.json, src/functionalTest/resources/features/F-007/S-082.td.json, src/functionalTest/resources/features/F-007/S-082.v1_1.td.json, src/functionalTest/resources/features/F-007/S-084.td.json, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilStaffOrgRolesTest.java
[AM-2730](https://tools.hmcts.net/jira/browse/AM-2730) _"Prod Civil role issue - Any user with a team leader role does not inherit the permissions of the staff role that it has responsibility for"_
Adjust tests for #1426
* Adjust FTA tests to allow run with and without `civil_wa_1_1` enabled.
* Adjust unit tests for Civil Drool rules
```
[ ] Yes
[x] No
```
=> AM-2730 Adjust tests for #1426

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.preview.template.yaml
[AM-2808](https://tools.hmcts.net/jira/browse/AM-2808) _"ORM Migrate from OSBA to ASO"_
Migrate ORM PREVIEW chart config from OSBA to ASO.
NB: this follow on from:
* hmcts/cnp-flux-config#23000
* hmcts/cnp-flux-config#23022
```
[ ] Yes
[x] No
```
=> AM-2808 ORM PREVIEW migrate from OSBA to ASO

src/main/resources/validationrules/publiclaw/publiclaw-admin-mapping.drl, src/main/resources/validationrules/publiclaw/publiclaw-caseworker-mapping.drl, src/main/resources/validationrules/publiclaw/publiclaw-ctsc-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawStaffOrgRolesTest.java
https://tools.hmcts.net/jira/browse/AM-2815
Update AM org role mapping for FPL staff
```
[ ] Yes
[x] No
```
=> COT-306 update fpl staff role mappings

src/main/resources/application.yaml
[AM-2638](https://tools.hmcts.net/jira/browse/AM-2638) _"Upgrade Spring Boot version for ORM service"_
Adjust flag controller config in #1344.
```
[ ] Yes
[x] No
```
=>  AM-2638 Adjust flag controller config in PR-1344

src/main/resources/validationrules/stcic/stcic-judicial-office-holder-mapping.drl, src/main/resources/validationrules/stcic/stcic-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialRoleMappingTest.java
https://tools.hmcts.net/jira/browse/AM-2714
Service has updated their config to include Principal Judge in their judicial org role mapping
```
[ ] Yes
[x] No
```
=> AM-2714:ST_CIC - added Principal Judge JOH mapping

src/functionalTest/resources/features/F-008/S-073.td.json
https://tools.hmcts.net/jira/browse/AM-2826
ORM FTAs updated as per eLink refresh.
[ ] Yes
[X] No
=> AM-2826: S-073 updated query.

src/main/resources/validationrules/employment/employment-admin-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentStaffOrgRolesTest.java
* [AM-2831](https://tools.hmcts.net/jira/browse/AM-2831) _"ET_WA - Final round of review and testing of combined feature branches for release Employment_WA_1.0"_
* [AM-2688](https://tools.hmcts.net/jira/browse/AM-2688) _"ET_WA - Add mapping rules in ORM for STAFF users"_
* [AM-2615](https://tools.hmcts.net/jira/browse/AM-2615) _"ET_WA - Drool JUnit testing in ORM and RAS applications for STAFF users"_
* [AM-2612](https://tools.hmcts.net/jira/browse/AM-2612) _"ET_WA - Add mapping rules in ORM for ET judges"_
* [AM-2687](https://tools.hmcts.net/jira/browse/AM-2687) _"ET_WA - Drool JUnit testing in ORM and RAS applications for JUDICIAL users"_
Code Review Changes For #1434
```
[ ] Yes
[*] No
```
=> AM-2831 Code Review Changes For #1434

build.gradle, src/functionalTest/resources/features/F-001/S-002.td.json, src/functionalTest/resources/features/F-001/S-007.td.json, src/functionalTest/resources/features/F-004/S-032.td.json, src/functionalTest/resources/features/F-005/S-043.td.json, src/functionalTest/resources/features/F-005/S-044.td.json
https://tools.hmcts.net/jira/browse/AM-2835
Configure arrays in FTAs so where possible they are unordered
=> AM-2835: Configure arrays in FTAs so where possible they are unordered

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2854
CVE-2023-34462 Suppression
```
[ ] Yes
[x] No
```
=> AM-2854 CVE-2023-34462 Suppression

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/AM-2844
Flyway config OutOfOrder trying to fix AAT deployment
```
[ ] Yes
[x] No
```
=> AM-2844 ET Flyway config OutOfOrder trying to fix AAT deployment

src/main/resources/validationrules/publiclaw/publiclaw-admin-mapping.drl, src/main/resources/validationrules/publiclaw/publiclaw-caseworker-mapping.drl, src/main/resources/validationrules/publiclaw/publiclaw-ctsc-mapping.drl, src/main/resources/validationrules/publiclaw/publiclaw-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawStaffOrgRolesTest.java
[COT-368](https://tools.hmcts.net/jira/browse/COT-368) - Update role mapping to include the additional work types
Update FPL staff/judicial org role work types
```
[ ] Yes
[x] No
```
=> Cot 368 update fpl staff judicial work types

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2854
CVE-2023-34462 Netty upgrade 4.1.94.Final
```
[ ] Yes
[x] No
```
=> AM-2854 CVE-2023-34462 Netty upgraded 4.1.94.Final

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/AM-2738
Nightly build slack messaging removed
```
[ ] Yes
[x] No
```
=> AM-2738 Nightly build slack messaging removed

Jenkinsfile_CNP, charts/am-org-role-mapping-service/values.preview.template.yaml, src/functionalTest/resources/features/F-004/S-031.td.json, src/functionalTest/resources/features/F-004/S-032.td.json, src/functionalTest/resources/features/F-005/S-042.td.json, src/functionalTest/resources/features/F-005/S-043.td.json, src/functionalTest/resources/features/F-005/S-044.td.json, src/functionalTest/resources/features/F-006/S-051.td.json, src/functionalTest/resources/features/F-006/S-052.td.json
https://tools.hmcts.net/jira/browse/AM-2858
Fix failing FTs
```
[ ] Yes
[x] No
```
=> SSCS_WA_1_0:WA FTs

Jenkinsfile_CNP, charts/am-org-role-mapping-service/values.preview.template.yaml
[AM-2762](https://tools.hmcts.net/jira/browse/AM-2762) SSCS_WA - Add mapping rules in ORM for STAFF users
[AM-2763](https://tools.hmcts.net/jira/browse/AM-2763) SSCS_WA - Add mapping rules in ORM for SSCS judges
SSCS_WA Additional WA Config - Release Endpoint Tweak
```
[ ] Yes
[x] No
```
=> AM-2762 AM-2763 SSCS_WA Additional WA Config - Release Endpoint Tweak

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2869
CVE-2023-34036 Suppression
```
[ ] Yes
[x] No
```
=> AM-2869 CVE-2023-34036 Suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2869
CVE-2023-34036 spring-hateoas 1.5.5
```
[ ] Yes
[x] No
```
=> AM-2869 CVE-2023-34036 spring-hateoas 1.5.5

src/main/resources/validationrules/stcic/stcic-judicial-office-holder-mapping.drl, src/main/resources/validationrules/stcic/stcic-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialOfficeMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicStaffOrgRoleTest.java
https://tools.hmcts.net/jira/browse/AM-2866
ST_CIC_WA addressing review comments - Unit test coverage improved
```
[ ] Yes
[x] No
```
=> AM-2866 - ST_CIC_WA: WA address review comments

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2885
CVE-2023-3635 Suppression
```
[ ] Yes
[x] No
```
=> AM-2885 CVE-2023-3635 Suppression

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2888 CVE-2023-34034 Suppression
https://tools.hmcts.net/jira/browse/AM-2889 CVE-2023-3782 Suppression
```
[ ] Yes
[x] No
```
=> AM-2888 CVE-2023-34034 AM-2889 CVE-2023-3782 Suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2888
CVE-2023-34034 Fix spring-security upgraded 5.7.10
```
[ ] Yes
[x] No
```
=> AM-2888 CVE-2023-34034 Fix spring-security upgraded 5.7.10

src/main/resources/validationrules/stcic/stcic-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialRoleMappingTest.java
https://tools.hmcts.net/jira/browse/COT-439
Fee paid judge role needs a bookable attribute for the user to be prompted by ExUI to create a booking
```
[ ] Yes
[x] No
```
=> COT-439 ST_CIC WA updated fee paid judge attr

build.gradle, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/CRDTopicConsumer.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/JRDTopicConsumer.java
https://tools.hmcts.net/jira/browse/AM-2891
Add @WithSpan annotation to JRD & CRD topic consumers
=> AM-2891: Add @WithSpan annotation to JRD & CRD topic consumers

charts/am-org-role-mapping-service/values.preview.template.yaml
[AM-2901](https://tools.hmcts.net/jira/browse/AM-2901) _"Adjust service bus namespace used in ORM Preview chart file"_
[DTSPO-14781](https://tools.hmcts.net/jira/browse/DTSPO-14781) _"Preview build failing as Azure Service Bus topics not created for PR"_
Update ASB Namespace value after change.
```
[ ] Yes
[x] No
```
=> AM-2901 Update ASB Namespace value

src/main/resources/db/migration/V20230816_2906__AM-2906_Enable_privatelaw_wa_1_2_Prod.sql
https://tools.hmcts.net/jira/browse/AM-2906
Enable `privatelaw_wa_1_2` ORM flag in PROD
```
[ ] Yes
[x] No
```
=> AM-2906 Enable privatelaw_wa_1_2 ORM flag in PROD

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/RoleV2.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilder.java, src/main/resources/judicialProfileSampleV2.json, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
https://tools.hmcts.net/jira/browse/AM-2871
AM-2871 json field names judiciary_role_name and judiciary_role_id corrected to jurisdiction_role_name and jurisdiction_role_id
```
[ ] Yes
[x] No
```
=> Am 2871 fix model element name

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2885
CVE-2023-3635 okio 3.5.0 dependencySet added
```
[ ] Yes
[x] No
```
=> AM-2885 CVE-2023-3635 okio 3.5.0 dependencySet added

src/main/resources/db/migration/V20230921_2938__AM-2938_Enable_publiclaw_wa_1_1_Prod.sql
https://tools.hmcts.net/jira/browse/AM-2938
Enable `publiclaw_wa_1_1` ORM flag in PROD
```
[ ] Yes
[x] No
```
=> AM-2938 Enable `publiclaw_wa_1_1` ORM flag in PROD

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2953
https://tools.hmcts.net/jira/browse/AM-2952
CVE-2022-4244 CVE-2022-4245 Shared Suppression
=> AM-2953 CVE-2022-4244 AM-2952 CVE-2022-4245 Shared Suppression

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20231002_484__COT-484_CIVIL_WA_1_2_base_flag_addition.sql, src/main/resources/validationrules/civil/civil-judicial-office-holder-mapping.drl, src/main/resources/validationrules/civil/civil-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilHearingJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java
https://tools.hmcts.net/jira/browse/COT-484
https://tools.hmcts.net/jira/browse/CIV-10123
Add new appointment **District Judge- Sitting in Retirement** with 3 roles:
- judge (with booking)
- fee-paid-judge
- hmcts-judiciary
**NB**: The creation of JOH object is behind the flag `civil_wa_1_2`
=> COT-484 Civil new appointment District Judge- Sitting in Retirement

src/functionalTest/resources/features/F-004/S-031.td.json, src/functionalTest/resources/features/F-004/S-032.td.json, src/functionalTest/resources/features/F-005/S-041.td.json, src/functionalTest/resources/features/F-005/S-042.td.json, src/functionalTest/resources/features/F-005/S-043.td.json, src/functionalTest/resources/features/F-005/S-044.td.json, src/functionalTest/resources/features/F-006/S-051.td.json, src/functionalTest/resources/features/F-006/S-052.td.json, src/functionalTest/resources/features/F-006/S-053.td.json, src/main/resources/validationrules/sscs/sscs-admin-mapping.drl, src/main/resources/validationrules/sscs/sscs-caseworker-mapping.drl, src/main/resources/validationrules/sscs/sscs-ctsc-mapping.drl, src/main/resources/validationrules/sscs/sscs-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsStaffOrgRolesTest.java
https://tools.hmcts.net/jira/browse/COT-550
https://tools.hmcts.net/jira/browse/SSCS-12044
Work types id updated to match id on _wa-task-management-api_. See _wa-task-management-api_ [code](https://github.com/search?q=repo%3Ahmcts%2Fwa-task-management-api+pre_hearing&type=code)
**NB**: SSCS_WA_1_0 flag enabled on AAT & Demo but not on Prod
=> COT-550 rename work type to pre_hearing post_hearing

src/main/resources/validationrules/stcic/stcic-admin-mapping.drl, src/main/resources/validationrules/stcic/stcic-caseworker-mapping.drl, src/main/resources/validationrules/stcic/stcic-other-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicStaffOrgRoleTest.java
https://tools.hmcts.net/jira/browse/COT-552
Remove region from sptribs staff role config as sptribs staff users should be able to work on all tasks/cases despite their ref data region.
=> COT-552 remove region from sptribs staff roles

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-3002 CVE-2023-5072
https://tools.hmcts.net/jira/browse/AM-3003 CVE-2023-44487
Shared Suppression
=> AM-3002 CVE-2023-5072 AM-3003 CVE-2023-44487 shared suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-3003 CVE-2023-44487 
https://tools.hmcts.net/jira/browse/AM-2968 CVE-2023-4586
netty upgrade 4.1.100.Final
=> AM-3003 CVE-2023-44487 netty upgrade 4.1.100.Final

infrastructure/main.tf, infrastructure/terraform.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2996
Provision terraform v15 server Perftest
=> AM-2996 Provision terraform v15 server Perftest

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-3012
CVE-2023-4586 netty 2nd Time - Suppression
=> AM-3012 CVE-2023-4586 netty 2nd Time - Suppression

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20231026_3018__AM-3018_PRIVATELAW_WA_1_3_base_flag_addition.sql, src/main/resources/validationrules/privatelaw/privatelaw-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPrivateLawJudicialRoleMappingTest.java
[AM-3018](https://tools.hmcts.net/jira/browse/AM-3018) _"PRIVATELAW circuit-judge role mapping changes"_
PRIVATELAW judge mapping changes for Circuit Judges.
=> AM-3018: PRIVATELAW circuit-judge role mapping changes

src/main/resources/db/migration/V20231030_3032__AM-3031_Enable_PRIVATELAW_WA_1_3_Prod.sql
[AM-3032](https://tools.hmcts.net/jira/browse/AM-3032) _"Enable `privatelaw_wa_1_3` ORM flag in PROD"_
[AM-3018](https://tools.hmcts.net/jira/browse/AM-3018) _"PRIVATELAW circuit-judge role mapping changes"_
Enable `privatelaw_wa_1_3` ORM flag in PROD.
> NB: This PR is dependent on the change in #1624 for [AM-3018](https://tools.hmcts.net/jira/browse/AM-3018) **being signed off by service team**.
=> AM-3032 Enable privatelaw_wa_1_3 ORM flag in PROD

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/AM-2983
Connect to v15 JBS ITHC - Remove 'ithc' from git branchesToSync
=> AM-2983 Connect to v15 JBS ITHC - Remove 'ithc' from git branchesToSync

infrastructure/main.tf, infrastructure/terraform.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2996
provision terraform postgres v15 perftest user host secrets
=> Am 2996 provision terraform postgres v15 perftest

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-2996
Provision Terraform Postgres v15 - subnet_suffix = "expanded"
=> AM-2996 Provision Terraform Postgres v15 - subnet_suffix = "expanded"

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.preview.template.yaml, charts/am-org-role-mapping-service/values.yaml, src/main/resources/application.yaml, src/main/resources/bootstrap.yml
https://tools.hmcts.net/jira/browse/AM-3048
Retire Bootstrap yaml in ORM
=> AM-3048 Retire Bootstrap yaml

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-2976
v15 Provision Expanded Subnet
=> AM-2976 Provision Terraform v15 server ITHC Expanded Subnet

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-2976
v15 Reprovision
=> AM-2976 v15 Reprovision

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2839
CVE-2023-35116 jackson upgraded to 2.15.3, Remove Suppression
=> AM-2839 CVE-2023-35116 jackson upgraded to 2.15.3, Remove Suppression

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-3065
CVE-2023-36052 Suppression
=> AM-3065 CVE-2023-36052 Suppression

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-3061
v15 Reader User Trigger ITHC, Perftest, Demo
=> AM-3061 v15 Reader User Trigger

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2840
CVE-2022-45688 Remove Suppression
=> AM-2840 CVE-2022-45688 Remove Suppression

orm-wiremocks-docker/mocks/wiremock/__files/jrd/refreshUserProfile.json.hbs
https://tools.hmcts.net/jira/browse/AM-2917
tidy up.
=> AM-2917 Tidy up

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-3012
AM-3012 CVE-2023-4586 netty 2nd Time Remove Suppression
=> AM-3012 CVE-2023-4586 netty 2nd Time Remove Suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-3090
CVE-2023-6378 Fix
=> AM-3090 CVE-2023-6378 Fix logbackVersion upgraded 1.2.13

Jenkinsfile_CNP, charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.preview.template.yaml, charts/am-org-role-mapping-service/values.yaml
[AM-2936](https://tools.hmcts.net/jira/browse/AM-2936)
Merging branch [AM-2936-add-preview-jbs](https://github.com/hmcts/am-org-role-mapping-service/tree/AM-2936-add-preview-jbs) into https://github.com/hmcts/am-org-role-mapping-service/tree/AM-2936-add-preview-ras to incorporate the JBS changes into one PR.
=> Am 2936 add preview jbs

src/main/resources/judicialProfileSample.json, src/main/resources/validationrules/sscs/sscs-judicial-office-holder-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsJudicialOfficeMappingTest.java
[COT-684](https://tools.hmcts.net/jira/browse/COT-684)
Removed a check on the ticket code 362 for Tribunal Member Financially Qualified in SSCS. Code is sittint under existing flag SSCS_WA_1_0 which is enabled in demo, aat and perftest.
=> COT-684 removed check on ticket code 362 for Tribunal Member Financially Qualified SSCS

renovate.json
https://tools.hmcts.net/jira/browse/AM-3095
Renovate Exclude befta-fw Pre Releases
=> AM-3095 Renovate Exclude befta-fw Pre Releases

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-3002
CVE-2023-5072 Fix json upgrade 20231013
=> AM-3002 CVE-2023-5072 Fix json upgrade 20231013

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSAM-91
CVE 2023 33202 Fix
=> DTSAM-91 CVE 2023 33202 fix

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.aat.template.yaml, charts/am-org-role-mapping-service/values.preview.template.yaml, charts/am-org-role-mapping-service/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DTSAM-100
Retire JRD V2 eLinks Config - Default config variables to true
=> DTSAM-100 Retire JRD V2 eLinks Config - Default config variables to true

charts/am-org-role-mapping-service/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSAM-104
Chart-java Upgrade 5.0.4
=> DTSAM-104 Chart-java Upgrade 5.0.4

src/main/java/uk/gov/hmcts/reform/orgrolemapping/data/BatchLastRunTimestampEntity.java, src/main/resources/db/migration/V20240108_99__GA-99-Create-table-batch_last_run_timestamp.sql, src/test/java/uk/gov/hmcts/reform/orgrolemapping/data/BatchLastRunTimestampTest.java
https://tools.hmcts.net/jira/browse/GA-99
PRM : Create table batch_last_run_timestamp
=> Ga 99 create table batch last run timestamp

src/main/resources/db/migration/V20240208_114__DTSAM-114_Enable_publiclaw_wa_1_2_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-114
publiclaw_wa_1_2 Enable in Prod, Demo, Perftest, ITHC
=> DTSAM-114 publiclaw_wa_1_2 Enable in Prod, Demo, Perftest, ITHC

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSAM-137
CVE-2023-34042 Suppression
=> DTSAM-137 CVE-2023-34042 Suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSAM-137
CVE-2023-34042 spring-security upgraded to 5.7.11
=> DTSAM-137 CVE-2023-34042 spring-security upgraded to 5.7.11

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSAM-154
CVE-2024-25710 Suppression
=> DTSAM-154 CVE-2024-25710 Suppression

src/main/java/uk/gov/hmcts/reform/orgrolemapping/data/OrganisationRefreshQueueEntity.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/data/UserRefreshQueueEntity.java, src/main/resources/db/migration/V20240104_49__GA-49_Create_organisation_refresh_queue_table.sql, src/main/resources/db/migration/V20240108_50__GA-50_Create_user_refresh_queue_table.sql
https://tools.hmcts.net/jira/browse/GA-170
Update organisation_refresh_queue and user_refresh_queue queue to capture retry and retry_after
=> GA-170 update org/user refresh queues

src/main/java/uk/gov/hmcts/reform/orgrolemapping/data/UserRefreshQueueEntity.java, src/main/resources/db/migration/V20240108_50__GA-50_Create_user_refresh_queue_table.sql
[GA-163](https://tools.hmcts.net/jira/browse/GA-163)
* Add `user_last_update` column
* Default the `last_updated` column to the current timestamp
=> Update UserRefreshQueueEntity to include user last updated property

src/functionalTest/resources/features/common/PushMessageToSend2CrdTopic.td.json, src/functionalTest/resources/features/common/PushMessageToSend2JrdTopic.td.json, src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/TopicController.java
[DTSAM-150](https://tools.hmcts.net/jira/browse/DTSAM-150) _"Add ORM FTAs test to verify CRD and JRD service bus messages"_
Change response format used in TopicController's APIs.
> **NB: this is a PATCH PR for #1779**
=> DTSAM-150 Change TopicController's response format

src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/data/UserRefreshQueueRepositoryIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ProfessionalUserIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/helper/IntTestDataBuilder.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/data/UserRefreshQueueEntity.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/data/UserRefreshQueueRepository.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/ProfessionalUserData.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/constants/PrmConstants.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/ProfessionalUserBuilder.java, src/main/resources/db/migration/V20240108_50__GA-50_Create_user_refresh_queue_table.sql, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/ProfessionalUserBuilderTest.java
[GA-163](https://tools.hmcts.net/jira/browse/GA-163)
* Update the migration to default the last_updated column to `now()`
* rename field `lastUpdated` to `userLastUpdated`
=> GA-163 Update PRM Process 4 to update the user last updated column

src/main/java/uk/gov/hmcts/reform/orgrolemapping/monitoring/models/EndStatus.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/monitoring/models/ProcessMonitorDto.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/monitoring/models/RecordStatus.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/monitoring/service/ProcessEventTracker.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/monitoring/models/ProcessMonitorDtoTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/monitoring/service/ProcessEventTrackerTest.java
[GA-185](https://tools.hmcts.net/jira/browse/GA-185)
Add a model and component to simplify tracking PRM Process events
=> GA-185 add process monitoring component

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/CaseDefinitionService.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/CaseDefinitionServiceTest.java
[GA-186](https://tools.hmcts.net/jira/browse/GA-186)
Track when PRM Process 1 has started and completed
=> GA-186 Track PRM Process 1

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-3025
Schema Owner Fix
=> AM-3025 Migrate Data ORM AAT - Schema Owner Fix

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-3025
Migrate Data ORM AAT - Schema Owner Bump 2
=> AM-3025 Migrate Data ORM AAT - Schema Owner Bump 2

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/OrganisationService.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/OrganisationServiceTest.java
[GA-187](https://tools.hmcts.net/jira/browse/GA-187)
Track PRM Process 2 Start and Complete events
=> GA-187 add event logging for process 2

src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/data/AccessTypesRepositoryIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/data/TestData.java, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/CaseDefinitionServiceIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/dto/AccessTypeString.java, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/dto/Jurisdiction.java, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/dto/OrganisationProfile.java, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/dto/OrganisationProfiles.java, src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/dto/Role.java, src/integrationTest/resources/sql/insert_access_types.sql, src/integrationTest/resources/sql/insert_civil_existing_access_types.sql, src/integrationTest/resources/sql/insert_civil_mismatch_existing_access_types.sql, src/integrationTest/resources/sql/insert_existing_profiles_refresh_queue.sql
=> refactored integration test for GA-54

src/main/resources/validationrules/employment/employment-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentHearingJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentJudicialRoleMappingTest.java
[COT-818](https://tools.hmcts.net/jira/browse/COT-818)
Adding the case-allocator role to the EMPLOYMENT Employment Judge-Salaried joh
=> COT-818 - adding case allocator for salaried judge

src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ProfessionalUserIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ProfessionalUserService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/monitoring/models/ProcessMonitorDto.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ProfessionalUserServiceTest.java
[GA-189](https://tools.hmcts.net/jira/browse/GA-189)
Track PRM Process 4 Start and Complete events
=> Ga 189 track process events v2

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-3061
v15 Reader User Trigger 3 AAT, ITHC, Perftest, Demo
=> AM-3061  v15 Reader User Trigger 3 AAT, ITHC, Perftest, Demo

src/main/resources/db/migration/V20240319_143__DTSAM-143_Enable_publiclaw_wa_1_3_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-143
Enable 'publiclaw_wa_1_3' ORM flag in PROD
=> DTSAM-143 Enable 'publiclaw_wa_1_3' ORM flag in PROD

src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ProfessionalUserIntegrationTest.java, src/integrationTest/resources/sql/insert_organisation_profiles_retry_3.sql, src/main/java/uk/gov/hmcts/reform/orgrolemapping/data/OrganisationRefreshQueueRepository.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ProfessionalUserService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/monitoring/models/ProcessMonitorDto.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ProfessionalUserServiceTest.java
https://tools.hmcts.net/jira/browse/GA-181
Subtask to update process 4 with retry mechanism mentioned in parent ticket [GA-172](https://tools.hmcts.net/jira/browse/GA-172)
=> GA-181 p4 with retry approach

src/main/resources/db/migration/V20240321_836__COT-836_Enable_EMPLOYMENT_WA_1_1_base_flag.sql
[COT-836](https://tools.hmcts.net/jira/browse/COT-836)
Enable employment_wa_1_1 in production to enable new rule created under COT-835.
=> COT-836 - enable employment_wa_1_1 in prod.

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSAM-185
Suppress 
CVE-2024-1597
=> DTSAM-185 : CVE Suppression CVE-2024-1597

src/functionalTest/resources/features/F-006/S-060.td.json, src/functionalTest/resources/features/F-006/S-060_JRDTribunalMemberFeePaidUser.td.json
https://tools.hmcts.net/jira/browse/DTSAM-239
Fix to the broken master pipeline. Case in s-060 had a change to the region after refresh which prevented it from getting sscs roles. New case created, but case has no end date, so check on this removed from test.
=> DTSAM-239 - fix broken pipeline due to altered functional test case.

src/functionalTest/resources/features/F-006/S-057.td.json, src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilder.java, src/main/resources/validationrules/sscs/sscs-ctsc-mapping.drl, src/main/resources/validationrules/sscs/sscs-judicial-org-role-mapping.drl, src/main/resources/validationrules/sscs/sscs-mulit-region.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsStaffOrgRolesTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/RoleAssignmentAssertHelper.java
[DTSAM-183](https://tools.hmcts.net/jira/browse/DTSAM-183) _"SSCS Multi-region for CTSC in England & Wales"_
SSCS CTSC Multi-region for England & Wales.
**NB: Also updates SSCS Judicial Multi-region for South West & Wales.**
=> DTSAM-183 SSCS Multi-region for CTSC

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20240403_182__DTSAM-182_PRIVATELAW_WA_1_4_base_flag_addition.sql, src/main/resources/validationrules/privatelaw/privatelaw-other-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolBase.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPrivateLawJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPrivateLawOtherGovDeptStaffRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPrivateLawStaffOrgRolesTest.java
[DTSAM-182](https://tools.hmcts.net/jira/browse/DTSAM-182) _"Removal of listed-hearing-viewer for OGA Roles"_
Private Law: changes to listed-hearing-viewer mappings.
=> DTSAM-182 PRL OGA listed-hearing-viewer changes

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DTSAM-255
Increase feign timeout to 15 seconds
=> DTSAM-255 Increase feign timeout to 15 seconds

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.preview.template.yaml, charts/am-org-role-mapping-service/values.yaml
[AM-2936](https://tools.hmcts.net/jira/browse/AM-2936) _"Pipeline improvements: reconfigure ORM PREVIEW chart to use an independent version of RAS and JBS"_
Rename subchart conditions to reduce chance names clash with others.
> NB: This PR is a patch to #1689.
> NB: see test PRs: 
> * #1860
> * #1861
> * #1862
=> AM-2936 patch to PR 1689

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20240415_258__DTSAM-258_EMPLOYMENT_WA_1_3_base_flag_addition.sql, src/main/resources/validationrules/employment/employment-judicial-office-holder-mapping.drl, src/main/resources/validationrules/employment/employment-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentHearingJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentJudicialRoleMappingTest.java
https://tools.hmcts.net/jira/browse/DTSAM-258
Added new judicial appt for ET - **Vice-President, Employment Tribunal (Scotland)**
=> DTSAM-258 ET appt Vice-President, Employment Tribunal (Scotland)

src/main/resources/db/migration/V20240415_259__DTSAM-259_Enable_employment_wa_1_3_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-259
Enable 'employment_wa_1_3' ORM flag in PROD
=> DTSAM-259 Enable 'employment_wa_1_3' ORM flag in PROD

src/main/resources/db/migration/V20240415_142__DTSAM-142_Enable_civil_wa_1_4_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-142
Enable 'civil_wa_1_4' ORM flag in PROD
=> DTSAM-142 Enable 'civil_wa_1_4' ORM flag in PROD

src/main/resources/db/migration/V20240417_3076__AM-3076_Enable_sscs_wa_1_0_Prod.sql
https://tools.hmcts.net/jira/browse/AM-3076
Enable sscs_wa_1_0 in Prod
=> AM-3076 Enable sscs_wa_1_0 in Prod

src/functionalTest/resources/features/F-005/F-005.feature, src/functionalTest/resources/features/F-005/S-041.td.json, src/functionalTest/resources/features/F-006/F-006.feature, src/functionalTest/resources/features/F-006/S-053.td.json, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20240419_265__DTSAM-265_SSCS_WA_1_2_base_flag_addition.sql, src/main/resources/validationrules/sscs/sscs-admin-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsStaffOrgRolesTest.java
https://tools.hmcts.net/jira/browse/DTSAM-265
Remove region from SSCS dwp & hmrc role assignments
=> DTSAM-265 remove region from SSCS dwp hmrc

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20240423_274__DTSAM-274_SSCS_WA_1_3_base_flag_addition.sql, src/main/resources/validationrules/sscs/sscs-judicial-office-holder-mapping.drl, src/main/resources/validationrules/sscs/sscs-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsJudicialOfficeMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsJudicialRoleMappingTest.java
https://tools.hmcts.net/jira/browse/DTSAM-274
SSCS_WA_1_3 Add 2 new judicial appointments for SSCS
- Judge of the First-tier Tribunal
- Member of the First-tier Tribunal (sitting in retirement)
=> Dtsam 274 two new sscs appt

src/main/resources/db/migration/V20240425_266__DTSAM-266_Enable_sscs_wa_1_2_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-266
Enable sscs_wa_1_2 ORM flag in PROD
=> DTSAM-266 Enable sscs_wa_1_2 ORM flag in PROD

src/main/resources/db/migration/V20240425_275__DTSAM-275_Enable_sscs_wa_1_3_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-275
Enable sscs_wa_1_3 ORM flag in PROD
=> DTSAM-275 Enable sscs_wa_1_3 ORM flag in PROD

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.yaml
https://tools.hmcts.net/jira/browse/DTSAM-252
Helm chart upgrade - chart-java 5.2.0 ,autoscaling disabled
=> DTSAM-252 Helm chart upgrade - chart-java 5.2.0 ,autoscaling disabled

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/AM-3046
Decommission V11 DB - Unsync ITHC branch from Master branch
=> AM-3046 Decommission V11 DB - Unsync ITHC branch from Master branch

Jenkinsfile_CNP
Reverts hmcts/am-org-role-mapping-service#1912
=> Revert "AM-3046 Decommission V11 DB - Unsync ITHC branch from Master branch"

src/functionalTest/resources/features/F-006/S-059.td.json, src/functionalTest/resources/features/F-006/S-059_JRDTribunalJudgeFeePaidUser.td.json, src/functionalTest/resources/features/F-010/S-107_JRDEmploymentJudgeFeePaidUser.td.json
https://tools.hmcts.net/jira/browse/DTSAM-324
Replaced expired fee paid user ids.
=> DTSAM-324: Fix ORM FTAs that have expired judicial appointments

infrastructure/terraform.tf
https://tools.hmcts.net/jira/browse/DTSAM-325
Upgrade azurerm to 3.105.0 after V11 Decommission
=> DTSAM-325 Upgrade azurerm to 3.105.0 after V11 Decommission

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSAM-320
Remove the custom V15 key vault secrets
=> DTSAM-320 Remove the custom V15 key vault secrets.

Jenkinsfile_CNP, Jenkinsfile_nightly, src/functionalTest/resources/features/F-001/F-001.feature, src/functionalTest/resources/features/F-002/F-002.feature, src/functionalTest/resources/features/F-003/F-003.feature, src/functionalTest/resources/features/F-004/F-004.feature, src/functionalTest/resources/features/F-005/F-005.feature, src/functionalTest/resources/features/F-006/F-006.feature, src/functionalTest/resources/features/F-007/F-007.feature, src/functionalTest/resources/features/F-008/F-008.feature, src/functionalTest/resources/features/F-009/F-009.feature, src/functionalTest/resources/features/F-010/F-010.feature, src/functionalTest/resources/features/F-011/F-011.feature
[DTSAM-336](https://tools.hmcts.net/jira/browse/DTSAM-336) _"ORM FTAs may fail if Ref-Data services are unavailable. Add EV flag option to disable those FTAs if needed"_
Added CASEWORKER_FTA_ENABLED and JUDICIAL_FTA_ENABLED flags.
> NB: test PRs:
> * #1944
> * #1945
> * #1946
> * #1947
=> DTSAM-336: CASEWORKER_FTA_ENABLED and JUDICIAL_FTA_ENABLED flags.

Jenkinsfile_CNP, Jenkinsfile_nightly
[DTSAM-339](https://tools.hmcts.net/jira/browse/DTSAM-339) _"Reactivate JRD FTAs in ORM once test user appointments are restored "_
Reactivate JRD FTAs: remove override of JRD FTA flag in jenkins config.
=> DTSAM-339 Reactivate JRD FTAs

src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerRefreshJobIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshController.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestrator.java
[DTSAM-293](https://tools.hmcts.net/jira/browse/DTSAM-293) _"Investigate New Judicial intermittent RefreshControllerRefreshJobIntegrationTest tests"_
Refactor Refresh Controller's RefreshJob integration tests.
=> DTSAM-293 Refresh Controller's RefreshJob integration tests

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/DTSAM-380
Temp Disable ASB Functional Tests
=> DTSAM-380 Temp Disable ASB Functional Tests

build.gradle
https://tools.hmcts.net/jira/browse/DTSAM-382
GIT_COMMIT null in Local Build Fix
=> DTSAM-382 GIT_COMMIT null in Local Build

src/functionalTest/resources/features/F-007/F-007.feature, src/functionalTest/resources/features/F-007/S-062.td.json, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20240702_360__DTSAM-360_CIVIL_WA_1_6_base_flag_addition.sql, src/main/resources/validationrules/civil/civil-admin-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilStaffOrgRolesTest.java
https://tools.hmcts.net/jira/browse/DTSAM-360
https://tools.hmcts.net/jira/browse/DTSCCI-397
Add `routine_work` work type to Civil RA - `hearing-centre-team-leader` & `hearing-centre-admin`
=> DTSAM-360 civil wa update admin workTypes

src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrmFeatureToggleService.java
https://tools.hmcts.net/jira/browse/DTSAM-418
FeatureToggle checks in FTAs should fail when they receive an unexpected response from server
- #2006 
- #2009
=> Dtsam 418 update fta feature toggle exc handling orm

src/main/resources/validationrules/stcic/stcic-judicial-office-holder-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialOfficeMappingTest.java
https://tools.hmcts.net/jira/browse/DTSAM-421
update ST Tribunal Member Financial to Tribunal Member Financially Qualified
=> DTSAM-421 update ST Tribunal Member Financial to Tribunal Member Financially Qualified

charts/am-org-role-mapping-service/values.aat.template.yaml, charts/am-org-role-mapping-service/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/DTSAM-429
DTSAM-429 Staging Memory Config 2
=> DTSAM-429 Staging Memory Config 2

src/functionalTest/resources/features/F-012/F-012-Base-Root.td.json, src/functionalTest/resources/features/F-012/F-012.feature, src/functionalTest/resources/features/F-012/F-012_Test_Data_Base.td.json, src/functionalTest/resources/features/F-012/S-121.td.json, src/functionalTest/resources/features/F-012/S-121_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-012/S-121_PushMessageToCRDService.td.json, src/functionalTest/resources/features/F-012/S-121_SingleUserMultipleCaseworkerRolesIds.td.json, src/functionalTest/resources/features/F-012/S-122.td.json, src/functionalTest/resources/features/F-012/S-122_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-012/S-122_PushMessageToCRDService.td.json, src/functionalTest/resources/features/F-012/S-122_SingleUserMultipleHearingRolesIds.td.json, src/functionalTest/resources/features/F-012/S-123.td.json, src/functionalTest/resources/features/F-012/S-123_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-012/S-123_PushMessageToCRDService.td.json, src/functionalTest/resources/features/F-012/S-123_SingleUserMultipleHearingRolesIds.td.json, src/functionalTest/resources/features/F-012/S-124.td.json, src/functionalTest/resources/features/F-012/S-124_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-012/S-124_PushMessageToCRDService.td.json, src/functionalTest/resources/features/F-012/S-124_SingleUserMultipleHearingRolesIds.td.json, src/functionalTest/resources/features/F-012/S-125.td.json, src/functionalTest/resources/features/F-012/S-125_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-012/S-125_PushMessageToCRDService.td.json, src/functionalTest/resources/features/F-012/S-125_SingleUserMultipleHearingRolesIds.td.json
https://tools.hmcts.net/jira/browse/DTSAM-426
Added FTAs for Staff ORG Roles.
=> DTSAM-426: FTA scenarios for Staff ORG roles.

build.gradle
=> DTSAM-446 Move org.apache.poi Version to Var in Gradle

src/main/resources/db/migration/V20240808_394__DTSAM-394_Enable_civil_wa_1_7_Prod.sql
[DTSAM-394](https://tools.hmcts.net/jira/browse/DTSAM-394) _"Enable 'civil_wa_1_7' ORM flag in PROD"_
Enable `civil_wa_1_7` DB flag in ORM PROD.
=> DTSAM-394 Enable civil_wa_1_7 DB flag in PROD

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20240731_443__DTSAM-443_CIVIL_WA_1_8_base_flag_addition.sql, src/main/resources/validationrules/civil/civil-judicial-office-holder-mapping.drl, src/main/resources/validationrules/civil/civil-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilHearingJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java
https://tools.hmcts.net/jira/browse/DTSAM-443
Expand Civil JoH to include `Circuit Judge (sitting in retirement)`
=> DTSAM-443: `CIVIL_WA_1_8`:  + appt `Circuit Judge (sitting in retirement)`

src/functionalTest/resources/features/F-007/F-007.feature, src/functionalTest/resources/features/F-007/S-081.td.json, src/functionalTest/resources/features/F-007/S-082.td.json, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20240801_452__DTSAM-452_CIVIL_WA_1_9_base_flag_addition.sql, src/main/resources/validationrules/civil/civil-multi-region.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilHearingJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java
https://tools.hmcts.net/jira/browse/DTSAM-452
CIVIL Allow Salaried London/SE Judges to access work from both regions
=> DTSAM-452 CIVIL Salaried London/SE multi region RAs

charts/am-org-role-mapping-service/Chart.yaml, charts/am-org-role-mapping-service/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/DTSAM-484
ORM Update Preview Chart after JBS LD Decommission
=> DTSAM-484 ORM Update Preview Chart after JBS LD Decommission

src/functionalTest/resources/features/F-006/F-006.feature
[DTSAM-485](https://tools.hmcts.net/jira/browse/DTSAM-485) _"Fix failing ORM FTAs after JRD test data change"_
Temp disable of failing FTA F-006 S-161 "must successfully create judicial role mapping for President of Tribunal - Salaried appointment"
=> DTSAM-485 temp disable of failing FTA

src/functionalTest/resources/features/F-006/F-006.feature, src/functionalTest/resources/features/F-006/S-161.td.json, src/functionalTest/resources/features/F-006/S-161_JRDPresidentOfTribunalSalariedUser.td.json
https://tools.hmcts.net/jira/browse/DTSAM-493
Updated userId d91c2ff4-66ed-4576-bb83-a738941dfa33 for S-161.
Done.
=> DTSAM-493: Fix ORM SSCS FTA after JRD test data change

src/functionalTest/resources/features/F-006/S-161_JRDPresidentOfTribunalSalariedUser.td.json
https://tools.hmcts.net/jira/browse/DTSAM-493
Updated new user for SSCS FTA S-161
=> Updated SSCS test user for S-161.

src/main/resources/db/migration/V20240823_392__DTSAM-392_Enable_civil_wa_1_6_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-392
Enable 'civil_wa_1_6' #1979 ORM flag in PROD
See service testing ticket: https://tools.hmcts.net/jira/browse/DTSCCI-725
=> DTSAM-392 Enable `civil_wa_1_6` on PROD

src/main/resources/db/migration/V20240823_391__DTSAM-391_Enable_civil_wa_1_5_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-391
Enable 'civil_wa_1_5' #1971 ORM flag in PROD
See service testing ticket: https://tools.hmcts.net/jira/browse/DTSCCI-724
=> DTSAM-391 Enable `civil_wa_1_5` on PROD

src/main/resources/db/migration/V20240905_455__DTSAM-455_Enable_publiclaw_wa_1_4_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-455
Enable #2020 `PUBLICLAW_WA_1_4` ORM flag in PROD
See: https://tools.hmcts.net/jira/browse/DTSAM-459
=> DTSAM-455 Enable `publiclaw_wa_1_4` DB PROD Flag

src/test/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/CRDTopicConsumerNewTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/JRDTopicConsumerNewTest.java
[DTSAM-487](https://tools.hmcts.net/jira/browse/DTSAM-487) _"ORM Remove Old ASB"_
Refactor unit tests for the new CRD/JRD Topic Consumers.
> NB: This PR is a patch to #2071.
=> DTSAM-487 Refactor unit tests for Topic Consumers

charts/am-org-role-mapping-service/values.preview.template.yaml, src/main/resources/application.yaml, src/smokeTest/java/uk/gov/hmcts/reform/orgrolemapping/SmokeTest.java
https://tools.hmcts.net/jira/browse/DTSAM-487
Remove Old ASB - Default to New ASB
=> DTSAM-487 Remove Old ASB - Default to New ASB

src/main/resources/db/migration/V20240918_457__DTSAM-457_Enable_civil_wa_1_8_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-457
Enable 'civil_wa_1_8' ORM flag in PROD
=> DTSAM-457 Enable 'civil_wa_1_8' ORM flag in PROD

src/functionalTest/resources/features/F-005/F-005.feature, src/functionalTest/resources/features/F-006/F-006.feature, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20240906_506__DTSAM-506_SSCS_WA_1_5_base_flag_addition.sql, src/main/resources/validationrules/core/hearing-role-admin-global.drl, src/main/resources/validationrules/core/hearing-role-other-global.drl, src/main/resources/validationrules/sscs/sscs-admin-mapping.drl, src/main/resources/validationrules/sscs/sscs-other-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsStaffOrgRolesTest.java
https://tools.hmcts.net/jira/browse/DTSAM-506
- Migrated OGD roles from admin.drl file to more appropriately named drl file
- Added new ODG role `ibca` for SSCS roleId = 19
- Updated `listed-hearing-viewer` to include roleId = 19
> NB: This PR is has a dependency on hmcts/am-role-assignment-service#2329
=> SSCS_WA_1_5 DTSAM-506 add IBCA mapping rule

src/main/resources/db/migration/V20240930_466__DTSAM-466_Enable_civil_wa_1_9_Prod.sql
[DTSAM-466](https://tools.hmcts.net/jira/browse/DTSAM-466) _"Enable 'civil_wa_1_9' ORM flag in PROD"_
Enable 'civil_wa_1_9' ORM flag in PROD
=> DTSAM-466 Enable 'civil_wa_1_9' ORM flag in PROD

src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilHearingJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilStaffOrgRolesTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java
https://tools.hmcts.net/jira/browse/DTSAM-584
Expand Civil Drool test coverage of service code AAA7
=> DTSAM-584 Expand Civil Drool test coverage of service code AAA7

src/functionalTest/resources/features/F-012/S-128.td.json, src/main/resources/validationrules/stcic/stcic-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialRoleMappingTest.java
https://tools.hmcts.net/jira/browse/COT-912
- Remove bookable attribute from fee-paid-judge
- Remove Judge RA when a booking made
=> COT-912 ST_CIC remove booked judge role assignment

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSAM-88
CVE-2023-36052 azure remove suppression
=> DTSAM-88 CVE-2023-36052 azure remove suppression

src/functionalTest/resources/features/F-012/S-128.td.json, src/main/resources/validationrules/stcic/stcic-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialRoleMappingTest.java
Revert "COT-912 ST_CIC remove booked judge role assignment"
Reverts hmcts/am-org-role-mapping-service#2145
=> COT-917: Add removed judge and bookable for identified fee-paid judge

V20241209_929__COT-929_Enable_st_cic_wa_1_1_Prod.sql
https://tools.hmcts.net/jira/browse/COT-929
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
Enable new ST flag in prod
=> COT-929 Enable 'st_cic_wa_1_1' AM ORM flag in PROD

src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-081.td.json, src/main/resources/validationrules/civil/civil-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilHearingJudicialRoleMappingTest.java
https://tools.hmcts.net/jira/browse/COT-937
After the release of COT-905, it was identified by task management that the new work types should be all lower case, this change is just to action this chagne.
Minor change has been proven via functional and unit tests.
=> COT-937 - Removing upper case characters in new work types

src/functionalTest/resources/features/F-003 - Create IA Judicial Role Assignments/F-003.feature
[DTSAM-786](https://tools.hmcts.net/jira/browse/DTSAM-786) _"Temporarily disable and then fix the failing judicial FTAs in ORM"_
Temporarily disable FTA S-022 in ORM o unblock pipelines
=> DTSAM-786 Temporarily disable FTA S-022 in ORM

src/functionalTest/resources/features/F-003 - Create IA Judicial Role Assignments/F-003.feature, src/functionalTest/resources/features/F-003 - Create IA Judicial Role Assignments/JRDTribunalJudgeFeepaidUser.td.json
[DTSAM-786](https://tools.hmcts.net/jira/browse/DTSAM-786) _"Temporarily disable and then fix the failing judicial FTAs in ORM"_
Re-enable FTA F-003 > S-022 after change in IDAM ID
=> DTSAM-786 Re-enable FTA F-003 > S-022 after change in IDAM ID

src/main/resources/db/migration/V20250220_918__COT-918_Enable_civil_wa_2_1_Prod.sql
… release
https://tools.hmcts.net/jira/browse/COT-918
Added migration script to enable new 'civil_wa_2_1' script in prod
=> COT-918 Enable 'civil_wa_2_1' AM ORM flag in PROD

src/main/resources/db/migration/V20250305_149__DTSAM-149_Enable_iac_jrd_1_1_Prod.sql
[DTSAM-149](https://tools.hmcts.net/jira/browse/DTSAM-149) _"Enable 'iac_jrd_1_1' ORM flag in PROD"_
Enable 'iac_jrd_1_1' ORM flag in PROD
=> DTSAM-149 Enable 'iac_jrd_1_1' ORM flag in PROD

build.gradle, src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/F-007.feature, src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.03_AAA6.td.json, src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.03_AAA7.td.json, src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.04_AAA6.td.json, src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.04_AAA7.td.json, src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.09_AAA6.td.json, src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.09_AAA7.td.json, src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.10_AAA6.td.json, src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.10_AAA7.td.json, src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-062.td.json, src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-064.td.json, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20250226_945__COT-945_CIVIL_WA_2_2_base_flag_addition.sql, src/main/resources/validationrules/civil/civil-admin-mapping.drl, src/main/resources/validationrules/civil/civil-ctsc-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilStaffOrgRolesTest.java
https://tools.hmcts.net/jira/browse/COT-945
Added additional worktype for various roles for Civil
> NB: Test PRs:
> * #2267
=> COT-945 Added additional worktype for various roles for Civil

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/OrganisationService.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PrdService.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/data/AccessTypeTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/data/BatchLastRunTimestampTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PrdServiceTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AccessTypesBuilderTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/monitoring/service/ProcessEventTrackerTest.java
[DTSAM-799](https://tools.hmcts.net/jira/browse/DTSAM-799)
[GA_Prm_Master Sonarqube](https://sonarcloud.io/summary/new_code?id=am-org-role-mapping-service&pullRequest=1737)
Resolve sonarqube issues on GA_PRM_Master.
=> Dtsam 799 sonarqube issues

src/main/resources/db/migration/V20250305_672__DTSAM-672_Enable_privatelaw_wa_1_5_Prod.sql
[DTSAM-672](https://tools.hmcts.net/jira/browse/DTSAM-672) _"Enable 'privatelaw_wa_1_5' AM ORM flag in PROD"_
Enable 'privatelaw_wa_1_5' AM ORM flag in PROD
> NB: This is to enable the changes in PR #2220.
=> DTSAM-672 Enable 'privatelaw_wa_1_5' AM ORM flag in PROD

src/main/resources/db/migration/V20250317_781__DTSAM-781_Enable_publiclaw_wa_1_7_Prod.sql
[DTSAM-781](https://tools.hmcts.net/jira/browse/DTSAM-781) _"Enable 'publiclaw_wa_1_7' AM ORM flag in PROD"_
Enable 'publiclaw_wa_1_7' ORM flag in PROD.
> NB: This is to enable the changes in PR #2240.
=> DTSAM-781 Enable 'publiclaw_wa_1_7' ORM flag in PROD

Jenkinsfile_CNP, build.gradle
[
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)](https://tools.hmcts.net/jira/browse/DTSAM-812)
=> DTSAM-812 Upgrade Fortify Client to 1.4.8 AM(ORM/RAS/JBS) repos

Jenkinsfile_CNP
[DTSAM-815](https://tools.hmcts.net/jira/browse/DTSAM-815) _"Re-enable ORM ASB FTAs in PREVIEW"_
Re-enable ASB FTAs.
=> DTSAM-815 Re-enable ASB FTAs

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20250327_801__DTSAM-801_CIVIL_WA_2_4_base_flag_addition.sql, src/main/resources/validationrules/civil/civil-judicial-office-holder-mapping.drl, src/main/resources/validationrules/civil/civil-judicial-org-role-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilHearingJudicialRoleMappingTest.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java
[DTSAM-801](https://tools.hmcts.net/jira/browse/DTSAM-801) _"Add a Civil role mappings for Designated Civil Online Judge - Salaried"_
Add Civil mapping for 'Designated Civil Online Judge'.
=> DTSAM-801 Add 'Designated Civil Online Judge'

src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java, src/main/resources/db/migration/V20250410_840__DTSAM-840_PUBLICLAW_WA_1_9_base_flag_addition.sql, src/main/resources/validationrules/publiclaw/publiclaw-judicial-office-holder-mapping.drl, src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawJudicialRoleMappingTest.java
[DTSAM-840](https://tools.hmcts.net/jira/browse/DTSAM-840) _"Adjust JoH rules to cover - 'President of the Family Division' for FPL"_
Expand FPL JoH rules for 'President of the Family Division'.
=> DTSAM-840 Expand FPL JoH rules for 'President of the Family Division'

config/owasp/suppressions.xml
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)](https://tools.hmcts.net/jira/browse/DTSAM-843)
=> DTSAM 843 Suppress CVE tomcat

build.gradle, config/owasp/suppressions.xml
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)](https://tools.hmcts.net/jira/browse/DTSAM-843)
=> DTSAM-843 FIx the CVE  CVE-2025-24813 tomcat

src/main/resources/db/migration/V20250416_829__DTSAM-829_Enable_publiclaw_wa_1_8_Prod.sql
[DTSAM-829](https://tools.hmcts.net/jira/browse/DTSAM-829) _"Enable 'publiclaw_wa_1_8' AM ORM flag in PROD"_
Enable 'publiclaw_wa_1_8' ORM flag in PROD.
> NB: This is to enable the changes in PR #2293.
=> DTSAM-829 Enable 'publiclaw_wa_1_8' ORM flag in PROD

src/main/resources/db/migration/V20250416_833__DTSAM-833_Enable_publiclaw_wa_1_9_Prod.sql
[DTSAM-833](https://tools.hmcts.net/jira/browse/DTSAM-833) _"Enable 'publiclaw_wa_1_9' AM ORM flag in PROD"_
Enable 'publiclaw_wa_1_9' ORM flag in PROD.
> NB: This is to enable the changes in PR #2299.
=> DTSAM-833 Enable 'publiclaw_wa_1_9' ORM flag in PROD

Jenkinsfile_CNP
[CME-346](https://tools.hmcts.net/jira/browse/CME-346) _"Spring Boot 3 and Java 21 Upgrade Upgrade RARB"_
Resync ITHC branch after deployment of #2317 and hmcts/am-role-assignment-refresh-batch#777.
> NB: This is a revert of #1965.
=> CME-346 Spring Boot 3 Upgrade RARB - Resync ITHC

src/functionalTest/resources/features/F-013 - PRM Scheduler/F-013.feature, src/functionalTest/resources/features/F-013 - PRM Scheduler/S-013.01_VerifySolicitorProfileRefreshQueueValueExists.td.json, src/functionalTest/resources/features/F-013 - PRM Scheduler/S-013.02_MakeSolicitorProfileRefreshQueueValueActive.td.json, src/functionalTest/resources/features/F-013 - PRM Scheduler/S-013.02_VerifySolicitorProfileRefreshQueueValueIsNotActive.td.json, src/functionalTest/resources/features/common/test-support/prm/FindProfileRefreshQueue__Base.td.json, src/functionalTest/resources/features/common/test-support/prm/FindProfileRefreshQueue__PositiveResponse_Base.td.json, src/functionalTest/resources/features/common/test-support/prm/MakeProfileRefreshQueueActive__Base.td.json, src/functionalTest/resources/features/common/test-support/prm/MakeProfileRefreshQueueActive__PositiveResponse_Base.td.json, src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/testingsupport/PrmProfileRefreshQueueController.java, src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/testingsupport/domain/ProfileRefreshQueueValue.java, src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/testingsupport/PrmProfileRefreshQueueControllerTest.java
[DTSAM-814](https://tools.hmcts.net/jira/browse/DTSAM-814) _"Create Test Support controller/endpoint and FTAs to test end-to-end run of PRM processes 1,2 and 3"_
Expand PRM Process 2 Functional Tests to cover checks on profile queue.
> NB: This is a patch PR for #2286
=> DTSAM-814 Expand PRM Process 2 Functional Tests

charts/am-org-role-mapping-service/values.preview.template.yaml, src/functionalTest/resources/features/F-008 - Create PRL Staff and Judicial Role Assignments/F-008.feature, src/functionalTest/resources/features/F-008 - Create PRL Staff and Judicial Role Assignments/S-074.td.json, src/functionalTest/resources/features/F-008 - Create PRL Staff and Judicial Role Assignments/S-075.td.json, src/functionalTest/resources/features/F-008 - Create PRL Staff and Judicial Role Assignments/S-075_DeleteDataForRoleAssignments.td.json, src/functionalTest/resources/features/F-008 - Create PRL Staff and Judicial Role Assignments/S-075_JRDDistrictJudgeSalariedUser.td.json, src/functionalTest/resources/features/F-008 - Create PRL Staff and Judicial Role Assignments/S-075_PushMessageToJRDService.td.json
https://tools.hmcts.net/jira/browse/DTSAM-860
FTA For #2335
=> DTSAM-860 FTAs for FL401-Judge

build.gradle
https://tools.hmcts.net/jira/browse/DTSAM-913
Fortify Client upgrade to 1.4.9 from 1.4.8
=> DTSAM-913 Fortify client to Upgrade to from 1.4.8 to 1.4.9

src/main/resources/db/migration/V20250603_422__DTSAM-422_Enable_employment_wa_1_4_Prod.sql
[DTSAM-422](https://tools.hmcts.net/jira/browse/DTSAM-422) _"Enable 'employment_wa_1_4' ORM flag in PROD"_
Enable 'employment_wa_1_4' ORM flag in PROD.
> NB: This is to enable the changes in PR #2005.
=> DTSAM-422 Enable 'employment_wa_1_4' ORM flag in PROD

src/main/resources/db/migration/V20250603_876__DTSAM-876_Enable_employment_wa_1_5_Prod.sql
[DTSAM-876](https://tools.hmcts.net/jira/browse/DTSAM-876) _"Enable 'employment_wa_1_5' ORM flag in PROD"_
Enable 'employment_wa_1_5' ORM flag in PROD.
> NB: This is to enable the changes in PR #2328.
=> DTSAM-876 Enable 'employment_wa_1_5' ORM flag in PROD

src/main/resources/db/migration/V20250618_917__DTSAM-917_Enable_publiclaw_wa_2_0_Prod.sql
https://tools.hmcts.net/jira/browse/DTSAM-917
https://tools.hmcts.net/jira/browse/DTSAM-826
Enable 'publiclaw_wa_2_0' AM ORM flag in PROD
=> DTSAM-917 Enable 'publiclaw_wa_2_0' AM ORM flag in PROD

src/main/resources/db/migration/V20250710_961__DTSAM-961_Enable_privatelaw_wa_1_8_Prod.sql
[DTSAM-961](https://tools.hmcts.net/jira/browse/DTSAM-961) _"Enable 'privatelaw_wa_1_8' AM ORM flag in PROD"_
Enable 'privatelaw_wa_1_8' AM ORM flag in PROD.
> NB: This is to enable the changes in combined PR #2373:  see also
> * #2363
> * #2364
=> DTSAM-961 Enable 'privatelaw_wa_1_8' ORM flag in PROD

src/main/resources/db/migration/V20250811_556__DTSAM-556_Enable_publiclaw_hearing_1_0_Prod.sql
[DTSAM-556](https://tools.hmcts.net/jira/browse/DTSAM-556) _"Enable 'PUBLICLAW_HEARING_1_0' ORM flag in PROD"_
Enable 'publiclaw_hearing_1_0' ORM flag in PROD.
> NB: This is to enable the changes #2109.
=> DTSAM-556 Enable 'publiclaw_hearing_1_0' ORM flag in PROD

src/main/resources/db/migration/V20250811_635__DTSAM-635_Enable_publiclaw_wa_1_6_Prod.sql
[DTSAM-635](https://tools.hmcts.net/jira/browse/DTSAM-635) _"Enable 'publiclaw_wa_1_6' ORM flag in PROD"_
Enable 'publiclaw_wa_1_6' AM ORM flag in PROD.
> NB: This is to enable the changes #2175 & #2178.
=> DTSAM-635 Enable 'publiclaw_wa_1_6' ORM flag in PROD

src/functionalTest/resources/features/F-006 - Create SSCS Staff and Judicial Role Assignments/F-006.feature
[DTSAM-1021](https://tools.hmcts.net/jira/browse/DTSAM-1021) _"Fix ORM FTA scenario which has expired fee-paid role"_
Temp disable of FTA F-006 S-060 as fee-paid role has expired.
=> DTSAM-1021 Temp disable of FTA F-006 S-060
